name: Auto Publish On Tag Push

on:
    push:
        tags:
            - '*'

jobs:
    auto-publish:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - run: npm install
            - run: npm run auto_publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
